# Generated by Django 3.2.20 on 2024-10-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240924_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('imagenarration', models.CharField(max_length=200)),
                ('imagename', models.CharField(max_length=250)),
                ('FROM_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frm', to='myapp.user')),
                ('TO_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tom', to='myapp.user')),
            ],
        ),
    ]
