# Generated by Django 3.2.25 on 2024-12-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20241216_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='grp',
            name='imagefile',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
